[package]
name = "url_shortener"
version = "0.1.0"
authors = ["Alson Kemp", "Keith Yeung", "Chris Piraino"]

[dependencies]
byteorder = "*"
nickel = "*"
rusqlite = "*"
rustc-serialize = "0.3"
time = "0.1"

